### PR TITLE
Update dev dependencies and fix broken build

### LINKED ISSUE #9: Released build is missing built CSS and JS files
## Description

The released `2.0.0` version of this plugin is missing the following built CSS and JS files:

- `assets/css/admin/wc-prl-cl-admin.css`
- `assets/js/admin/wc-prl-cl-admin.js`

Screenshot 2024-08-26 at 16 49 26

This causes the those files to not load at runtime:

Screenshot 2024-08-26 at 16 21 30

Which causes style issues and missing functionality:

### Current (broken)

Screenshot 2024-08-26 at 16 14 31

- Arrows to move meta boxes are visible
- Formatting issues in **Shortcode** meta box
- **Copy shortcode** does not work (since JS did not load)

### Fixed (local branch -- once I have access I will create PR)

Screenshot 2024-08-26 at 16 08 00

- Things look correct
- **Copy shortcode** works

## Underlying build/dev dependecies issue

I believe the underlying issue is that the build is out-of-date and not functioning correctly. At least, I could not build it on my local system. `npm i` fails due to out-of-date dependencies and missing `python2`.

Screenshot 2024-08-26 at 16 59 29

Once I updated the dev dependencies to match those in the **WooCommerce Product Recommendations** repo, I was able to successfully build the project and the styles and functionality worked at runtime. (Rather than install `python2` in an attempt to get things working, I think it is better to update the build for this project to be in-sync/up-to-date with the base plugin repo, since that is a better dev experience.)

### PR DESCRIPTION
**Pull request by mattsherman**
## Description

This PR updates the dev dependencies and build scripts, allowing this project to be successfully built in the same dev environment as other extensions such as the base WooCommerce Product Recommendations.

Closes #9 

## Changes included

- `devDependencies` updated to be the same as the WooCommerce Product Recommendations repo
    - `node-sass` replaced with `sass`
    - `autoprefixer`'s `browsers` option changed to `overrideBrowserslist` to avoid deprecation notice
- `@somewherewarm/selectsw` dependency removed, as it is unused in this repo

## Testing instructions

On a system with **WooCommerce Product Recommendations** installed...

1. Clone repo
2. Run `npm i` - verify dependencies are installed without error (used to complain about missing `python2`)
3. Run `grunt build` - verify build completes without error
4. Activate plugin
5. Go to **WooCommerce** > **Recommendations** > **Custom Locations**
6. Add a custom location.
7. Edit the custom location and verify that the styling and functionality is correct... key points...
    - **Shortcode** meta box styling
    - **Copy shortcode** feature should work
8. Verify the following files were requested without error (if the above points in (7) are fine, this will be the case, but just to double-check!):
    - `assets/css/admin/wc-prl-cl-admin.css`
    - `assets/js/admin/wc-prl-cl-admin.js`

Screenshot 2024-08-26 at 16 08 00

### CODE REVIEW

**Review by nathanss — APPROVED** [review]
Tested and reviewed the code. Was able to build and run the extension successfully.

I think you need to add the issue to a milestone. Can you please do that?

**Comment by mattsherman** [comment]
> Tested and reviewed the code. Was able to build and run the extension successfully.

Thanks!

> I think you need to add the issue to a milestone. Can you please do that?

Done (this public repo didn't have any milestones, but there is no reason to not start using them! 😄)

**Review by xristos3490 — COMMENTED** [review]
Looking good, @mattsherman! Nice catch on the unused prop!

Before approving, how about adding a similar [`.nvmrc`](https://github.com/woocommerce/woocommerce-product-recommendations/blob/trunk/.nvmrc) file as well?

**Comment by mattsherman** [comment]
> Looking good, @mattsherman! Nice catch on the unused prop!
> 
> Before approving, how about adding a similar [`.nvmrc`](https://github.com/woocommerce/woocommerce-product-recommendations/blob/trunk/.nvmrc) file as well?

Great idea -- done in d8685c7!

**Pull request merged**
